coordinate_transformer:
  ros__parameters:
    sensor_offset:
    - 0.394966
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 3.141592653589
    map_origin_offset:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    source_frame: odom
    target_frame: map
    tf_timeout: 0.05
    odom_orientation_frame: base
    odin_pose_topic: /odin1/odometry_highfreq
    output_pose_topic: /odin1/relocation_1
    publish_transformed_pose: true
    publish_rate: 100.0
